apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: application-readonly
  namespace: application
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
